openapi: 3.0.3
info:
  title: Swagger API Template
  description: |-
    A simple example for a Swagger API Template
  version: 1.0.0
servers:
  - url: https://example-template.trinext.de/api/v1
paths:
  /status:
    get:
      summary: receive the current api status
      description: Multiple status values can be provided with comma separated strings
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value