services:
  #TODO replace "template" with the project name
  template-main: &service
    profiles:
      - main
    environment:
      - IMAGE_NAME=${IMAGE_NAME:?err}
      - BIND_PORT=${BIND_PORT:?err}
      - CONTAINER_NAME=${CONTAINER_NAME:?err}
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - ${BIND_HOST:-127.0.0.1}:${BIND_PORT}:${CONTAINER_PORT:-4567}
    restart: unless-stopped
    healthcheck:
      test: curl -f localhost:${CONTAINER_PORT:-4567}/status || exit 1
      interval: 30s
      timeout: 2s
      retries: 3
      start_period: 10s
      start_interval: 1s
  #TODO replace "template" with the project name
  template-staging:
    <<: *service
    profiles:
      - staging
  #TODO replace "template" with the project name
  template-dev:
    <<: *service
    profiles:
      - dev