name: Validate Pull Requests

on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  enforce-branching-strategy:
    uses: TriNext/JTK-Workflows/.github/workflows/enforce-branching-strategy.yml@main
  validate-branch-name:
    uses: TriNext/JTK-Workflows/.github/workflows/validate-branch-name.yml@main